export const API_ROUTES = {
  CHECK_USERNAME: "/auth/check-username",
  SIGNUP: "/auth/signup",
  SIGNIN: "/auth/signin",
  SIGNOUT: "/auth/signout",
  VERIFY_OTP: "/auth/verify-otp",
  RESEND_OTP: "/auth/resend-otp",
  FORGOT_PASSWORD: "/auth/forgot-password",
  VERIFY_FORGOT_PASSWORD_OTP: "/auth/verify-forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  ADMIN_SIGNIN: "/auth/admin/signin",

  WALLET_BALANCE: "/wallet/balance",
  WALLET_DEPOSIT: "/wallet/deposit",
  WALLET_WITHDRAW: "/wallet/withdraw",
  WALLET_TRANSACTIONS: "/wallet/transactions",

  POLLS: "/polls",
  POLL_DETAIL: "/polls/:id",
  POLL_STAKE: "/polls/:id/stake",
  USER_STAKES: "/user/stakes",
  USER_WINNINGS: "/user/winnings",
  DRAW_WINNER: "/polls/:id/draw",

  ADMIN_POLLS: "/admin/polls",
  ADMIN_POLL_BY_ID: "/admin/polls/:id",
  ADMIN_USERS: "/admin/users",
  ADMIN_TRANSACTIONS: "/admin/transactions",
  ADMIN_ANALYTICS: "/admin/analytics",
  USER_CLAIM_PRIZE: "/user/claim-prize",
  USER_TESTIMONIAL: "/user/testimonial",
} as const;

export const APP_ROUTES = {
  HOME: "/",
  LOGIN: "/auth/login",
  OTP_VERIFICATION: "/auth/otp-verification",
  REGISTER: "/auth/register",
  FORGOT_PASSWORD: "/auth/forgot-password",
  VERIFY_FORGOT_PASSWORD: "/auth/verify-forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  DASHBOARD: "/dashboard",
  POLLS: "/polls",
  MY_STAKES: "/my-stakes",
  TRANSACTIONS: "/transactions",
  ADMIN_DASHBOARD: "/admin/dashboard",
} as const;
