export const API_ROUTES = {
  CHECK_USERNAME: "/auth/check-username",
  SIGNUP: "/auth/signup",
  SIGNIN: "/auth/signin",
  SIGNOUT: "/auth/signout",
  VERIFY_OTP: "/auth/verify-otp",
  RESEND_OTP: "/auth/resend-otp",
  FORGOT_PASSWORD: "/auth/forgot-password",
  VERIFY_FORGOT_PASSWORD_OTP: "/auth/verify-forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  ADMIN_SIGNIN: "/auth/signin",

  WALLET: "/wallet",
  WALLET_DEPOSIT: "/wallet/deposit",
  WALLET_WITHDRAW: "/wallet/withdraw",
  WALLET_TRANSACTIONS: "/wallet/transactions",

  PRODUCT_CATEGORIES: "/catalog/categories",
  PRODUCTS: "/catalog/products",
  PRODUCT_DETAIL: "/catalog/products/:id",
  PRODUCTS_BY_CATEGORY: "/catalog/categories/:id/products",
  CATEGORY_STATS: "/catalog/categories/:categoryId/stats",
  DRAW_STATS: "/catalog/draws/stats",
  ENROLL_PRODUCT: "/catalog/products/enroll",
  MY_DRAWS: "/catalog/draws/joined",
  WON_DRAWS: "/catalog/draws/won",
  CLAIM_DRAW: "/catalog/draws/:id/claim",

  ADMIN_POLLS: "/admin/polls",
  ADMIN_POLL_BY_ID: "/admin/polls/:id",
  ADMIN_USERS: "/admin/users",
  ADMIN_TRANSACTIONS: "/admin/transactions",
  ADMIN_ANALYTICS: "/admin/analytics",
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_CATEGORY_BY_ID: "/admin/categories/:id",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_PRODUCT_BY_ID: "/admin/products/:id",
} as const;

export const APP_ROUTES = {
  HOME: "/",
  LOGIN: "/auth/login",
  OTP_VERIFICATION: "/auth/otp-verification",
  REGISTER: "/auth/register",
  FORGOT_PASSWORD: "/auth/forgot-password",
  VERIFY_FORGOT_PASSWORD: "/auth/verify-forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  POLLS: "/polls",
  MY_STAKES: "/my-stakes",
  TRANSACTIONS: "/transactions",
  ADMIN_DASHBOARD: "/admin/dashboard",
} as const;
